FROM node:6
MAINTAINER LiskHQ
LABEL description="Lisk Docker Image - Testnet" version="1.4.2"

# Install Essentials
WORKDIR /root
RUN apt-get update
RUN apt-get install -y curl git gzip libtool nano wget tar jq sudo postgresql-client-9.4

# Add Lisk User
RUN useradd lisk -s /bin/bash -m
RUN echo "lisk:password" | chpasswd
RUN echo "%lisk ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

VOLUME ["/home/lisk/lisk"]

# Install Lisk
USER lisk
WORKDIR /home/lisk
RUN wget https://downloads.lisk.io/lisk/test/lisk-source.tar.gz -O lisk-source.tar.gz
RUN tar -zxvf lisk-source.tar.gz
RUN mv -f lisk-source src
RUN rm lisk-source.tar.gz
WORKDIR src
RUN npm install --production
RUN sed -i 's/"public": false,/"public": true,/g' config.json

# Install Lisk Node
RUN wget https://downloads.lisk.io/lisk-node/lisk-node-Linux-x86_64.tar.gz -O lisk-node-Linux-x86_64.tar.gz
RUN tar -zxvf lisk-node-Linux-x86_64.tar.gz
RUN rm lisk-node-Linux-x86_64.tar.gz

# Install Start Lisk
WORKDIR /home/lisk
USER root
ADD scripts/entrypoint.sh /home/lisk
RUN chown lisk:lisk entrypoint.sh
RUN chmod ug+x entrypoint.sh
ADD scripts/start_lisk /home/lisk
RUN chown lisk:lisk start_lisk
RUN chmod ug+x start_lisk

USER lisk

ENV TOP=true
ENV TERM=xterm

EXPOSE 8000
ENTRYPOINT ["./entrypoint.sh", "test"]
