FROM ubuntu
MAINTAINER LiskHQ
LABEL description="Lisk Docker Image" version="1.1.0"

# Install Essentials
WORKDIR /~
RUN sudo apt-get update
RUN sudo apt-get install -y build-essential curl git gzip nano python wget tar

# Install Node.js
RUN curl -sL https://deb.nodesource.com/setup_0.12 | sudo -E bash -
RUN sudo apt-get install -y nodejs

# Install PostgreSQL
RUN curl -sL https://downloads.lisk.io/scripts/setup_postgres.Linux | sudo -E bash -
RUN sudo service postgresql start

# Configure PostgreSQL
RUN sudo -u postgres createuser --createdb lisk
RUN sudo -u postgres psql -c "ALTER USER \"lisk\" WITH PASSWORD 'password';"
RUN sudo -u postgres createdb -O lisk lisk_test

# Add Lisk User
RUN useradd lisk -s /bin/bash -m
RUN echo "lisk:password" | chpasswd
RUN echo "%lisk ALL=(ALL) ALL" >> /etc/sudoers
USER lisk

# Install Lisk
RUN wget https://downloads.lisk.io/lisk/test/lisk-source.tar.gz -O lisk-source.tar.gz
RUN tar -zxvf lisk-source.tar.gz
RUN mv -f lisk-source lisk
RUN rm lisk-source.tar.gz
WORKDIR lisk
RUN npm install --production

# Install Lisk Node
RUN wget https://downloads.lisk.io/lisk-node/lisk-node-Linux-x86_64.tar.gz -O lisk-node-Linux-x86_64.tar.gz
RUN tar -zxvf lisk-node-Linux-x86_64.tar.gz
RUN rm lisk-node-Linux-x86_64.tar.gz

# Install Start Lisk
RUN wget https://downloads.lisk.io/scripts/start_lisk -O start_lisk
RUN chmod ugo+x start_lisk

ENV TOP=true
ENV TERM=xterm

EXPOSE 7000
ENTRYPOINT ./start_lisk
